# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branza', models.CharField(max_length=200)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('wakat', models.CharField(blank=True, max_length=100)),
                ('wynagrodzenie', models.FloatField(blank=True, default=0)),
                ('opis', models.CharField(max_length=1000)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.Firma')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
