# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0002_auto_20180404_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='opis',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='wakat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='wynagrodzenie',
            field=models.FloatField(default=0),
        ),
    ]
