# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_auto_20180403_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='firma',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
    ]
