# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0005_auto_20180403_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(default='SOME_NAZWA_FIRMY', max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='data_utworzenia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='oferta',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wakat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wiek_dol',
            field=models.SmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wiek_gora',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wynagrodzenie',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='oferta',
            name='firma',
            field=models.ForeignKey(default='SOME_FIRMA', on_delete=django.db.models.deletion.CASCADE, to='projekt.Firma'),
        ),
    ]
