# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='firma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.Firma'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
