# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0009_auto_20180403_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='wiek_dol',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='wiek_gora',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='wynagrodzenie',
        ),
    ]
