# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0010_auto_20180403_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='opis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wiek_dol',
            field=models.SmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wiek_gora',
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='oferta',
            name='wynagrodzenie',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
