# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0011_auto_20180403_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(default='SOME_NAZWA_FIRMY', max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('ulica', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='oferta',
            name='wiek_dol',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='wiek_gora',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='oferta',
            name='firma',
            field=models.ForeignKey(default='SOME_FIRMA', on_delete=django.db.models.deletion.CASCADE, to='projekt.Firma'),
        ),
    ]
