# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0012_auto_20180403_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='firma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projekt.Firma'),
        ),
    ]
