# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0013_auto_20180403_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='firma',
        ),
        migrations.AlterField(
            model_name='oferta',
            name='opis',
            field=models.CharField(max_length=1000),
        ),
    ]
